apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoidmNoYXJyaWUiLCJwYXNzd29yZCI6IlRPTl9UT0tFTl9HSENSIiwiZW1haWwiOiJ0b24uZW1haWxAZXhhbXBsZS5jb20iLCJhdXRoIjoiZG1Ob1lYSnlhV1U2VkU5T1gxUlBTMFZPWDBkSVExST0ifX19
kind: Secret
metadata:
  name: ghcr-secret
  namespace: coreservice
type: kubernetes.io/dockerconfigjson
