---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: coreservice
spec:
  encryptedData:
    .dockerconfigjson: AgA/1+0bkO/Y/M3+Q0tYS/G3W59RY6i7s5N9WR2b2npAsZKe41xQJZeUUQLow+wUg0xNc3emzPGZfVwl78u/BM/8PGcw0iNFjNQv7ezXyMSKdEcNrv4nfo2zr4vjyiR+P7BFbhh4vYRaghtEdVlNStXiaKxUHeXBopOEYbuQfIjjQipytqXdR7YYTSMpBp4ZVBbd5eFHzRLaMjI+9N1+nKrM2WtILN1Jw7IBXjBN+9fiX0ghOGLg77iyO3MFyiqD9Xp8UsgpfUhiborjqv9Qgz8YobWC9BvZOWEJJPpWmzAvV543MJ+vvvv8UPOregk7/2trJLNdrK7f/PKBoIJTj92DuZM3hIuW92oWHFxC7XUYuoLV9B3R2KlEyLRnARguq3iEzTT9qliuLdWvh2k+KLV/gsp6yupcOmlrqGLW0WO2vOp65iYKco+vusj3QBA8Zc5gSsSnSYZXZwsJJT15JV/G/9tfMb0uffRRAbtq+IbCXMgsVdyaeGLq+VbdQvbzDHxBtaML1pFxW8iKYBrISMsU1sk7Q/PK7cnSVhRWy8pW18AV86/CCn0+hAKqzW08QadkOVyr58vvJsP2AoEpP4IWJbv9d5zWHs+ElTOWc/lgHvJnwzHM58ZFr4w1bB/iPk5rBYyqlzh3BZ1hLgBK0250qiwSKHMHq+kNwv3OGt1DMMrCVLZAzNYtoOoOBC/iPnoqFRfMbJUMwdETzzwuUgFVyLy0mgH2O1KL2B/1czkj/RKbVkelMySpynnKXkCigGi3siRiSqPkDwicC18XbpKhfLMTXmQw4YE76YC44tl2i1AQsoQT3gno9tRzkIz6u8cYArFk26U7GbMb56EcAijLeAxEPbcIOfOH9drkm3mcgi/+pvKxcbmHbhHWoNu7+SO4Ym2HShQvqSjW3UyMXS4aIIPL3YVNdKBIl33qm8sMi44=
  template:
    metadata:
      name: ghcr-secret
      namespace: coreservice
    type: kubernetes.io/dockerconfigjson
