---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: coreservice
spec:
  encryptedData:
    .dockerconfigjson: AgBsxKcckFxlukCEsJL4xqosZZUlgoVSOVsYYUm7rmQGX2jyhc4eC9mLFZ5H7hRUr5SGCYLWokdU68tne8BjnYDB5XjtHAcvK6Jn9sSzxoRC4cf+PtptJpj+dXdX8hf5K9BS5IQXJOh3E//md3PPt1r8mba43vZQwL1gfHhUE1k+l195Cs1Yewapxb/Sx6ARVoJMK0qo3LVpoFK1FhVvBpSfhSHhcqJSnhdjZuzdDNjroaS2bTYEWG6LPdhBE6cDUoZWBwyRWd/PCPSQp3zpWweuEcRv+fBBsedA9Ny7A4GKVV8x7B+HQ75XzY5+SlWRk5ylt/gGAVKWxskTwoHaGe0Sb5HX89ZsM9WgENLGfgXO9cwcT/YFBj4vYXaMsN2cyzfI9CwlJPGysCl6RkgBoSHb6o3SHmldeXe7Ij4E7qVv1msHkujWqnMh6M8MH18G1bqM8Q+cutgg/dLDgcNIybwhsCYOUHAh2U0gCKqhQiXybtrcc8yhlpWLRaTinbZsMveR8FQ98Joxj298/SK9rs0lUjBdanJh3c8vHVjdI5fPDrQ6THkGhdCqwCL4Htjq3aEdu+EUxJeBxuZ2aa/DME6WzV9k/V70v0iaZqVCTcuHUZ8ocrwOgcbxe3uTTiuAyJuZn6ochc+qq9XSRx+L/Nci+Wentiv/PIm/YA0fNjaqE1+6Pf45fC/2lvWVWozrtk5kqo+lZiwH7JJj75trm0gEn450DEX4aKYYfhTsEUNp/pQiV0X0nNOv7R1Tq6VKVlIrlV0lDQjRIMT/g4JKsyBf8EdvxgTIsb+F+Ah/Jd1SW8MBm5beH56FMIPoy3tJmNlT74Smdpq6Ml0BdhuovfEujcpbuYsbdZ9usp4/HnJIaQwFFCLbUSa8tuG+mk5YQCQNXl/e84loGTvcAyCOFeoRYn8Z3OzQoiMuJNZQA5Iqllk=
  template:
    metadata:
      name: ghcr-secret
      namespace: coreservice
    type: kubernetes.io/dockerconfigjson
