spring.application.name=demo

spring.datasource.url=jdbc:h2:mem:coreservice;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.authentication=DEBUG
logging.level.org.springframework.security.authentication=DEBUG
logging.level.org.springframework.security.core.userdetails=DEBUG

logging.level.org.springframework.security=TRACE

app.security.token=change-me
app.security.salt=change-me

management.endpoints.enabled-by-default=false
management.endpoint.cloudfoundry.enabled=false

transfer.seuilSensibilite=1000