apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: coreservice

resources:
  - namespace.yaml
  - ../../base
  - sealedsecret-ghcr.yaml

patchesStrategicMerge:
  - patch-deployment.yaml
  - patch-ingress.yaml