apiVersion: apps/v1
kind: Deployment
metadata:
  name: coreservice
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: coreservice
          image: ghcr.io/vcharrie/coreservice:a9ba2dfd768b2039595eab3b53cc7172f4b0c1d7
