---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: coreservice
spec:
  encryptedData:
    .dockerconfigjson: AgAGYBp73oBBv9UX8DVHVH72ZpbCWDs2n56KtJb/60j6cqk4gd2b+cRPa5sz4/PQbvBbRA/2OtUm8QEYBKdLnYCae4vHS10OFJ7LL4oH5uvqnW/tNg4XBqiIId7aiAbRaqYEIUJLzAaHxW9eLcBCSL7OeCsYDFpm3GhpZJ6g2MdJLSizuIMAfsV0ESasis9HOwTnk6/zDXD4YmxP13SR+y6RjfQcCD0jnOZxN8Z7pjeWgSsk/mZ144zL7koEx939tcATW4FmBFKBKpNha2RMXkY4i7w6SMeVilSj08J0H6HihEMwFC18tV6rlJToazmB75hJqhKqKRHPuVwaxktk1rEFmjgwest265gKILa2m7Qu7YiYFzu3CqUFEmWqn8TQNUXL1dB8+8AICjuq7zyiWwRHuDFo4bp/xxigbQI/LbyVWr8Ab/K4hnSmE4PeLAFQfESXJIzBSNoggc+rcrbVCVYCE8AT1vA3FmDGdfCMZbcBYQpVRsmUWH3piWcJH/TSqVJ7t+VEdFX+2WMdeUz/HyNItaePmtIK7ewVhh+skZMmYvMHarCeUTfOLJvYywD3QhLW/AhVQo1HwMTtUe0AivKONkIYZOBLwtC8AU/QmWmyQExTWPPFQ8DBLBYoYiBUxQdzybrqObfFSW1KBMYg8FFCx3gjVlAAR5zON/hiY8s542LN0u3jzdX7mVDEoXoEIZbtDBicsIf+nmHsasssnPJNS9jztKbfXhMckNlnFdDo/Ni+zUAHXrK8zuAkQbcfBZqM5dUL5oN0sME0ap/f1ZcOMobcq4p684PaqrY4BTq8BJ/BC7ez9WU9AkfKIc/qGti57+XspEGQjW4Qwi8GOBNh0fpe7ManC/DRy92GY64yKAeFpX7GBIZx+0QdQKXRUb8JS1pXYnLz+vxzpvKo7s/fc0/vIyz9P7OG+vIG2zNEdhw=
  template:
    metadata:
      name: ghcr-secret
      namespace: coreservice
    type: kubernetes.io/dockerconfigjson
