---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: coreservice
spec:
  encryptedData:
    .dockerconfigjson: AgBUI5A/uS+9zueXAut08ytTHPvR8cqt0ubY5qU0KwTIRGq2c8zWASmBQ3WfRY+YM5IUe6IwiZkDQwgogP0kDA6+GZK+6L6u3SJ4oWgCN76pOnqDfYytTCPDh0LNuoBdtupaBe5SLIeSMoE17TWnF3KdKa5Jwg2A8dIeedxMWhAdNg/VCcKSOJ+uPyAtmZy+68V1VcuAy1WyKXhoe0odF7JeRKeUeG+6g4Z6Z4acVw5I4+KzFYZottHVgPYr8bvUHIc8LphCQqh/+Cv2G4+pXcBS9FOSvhpasSoM7v81FUunzB8TkpvbRU5Scg4DLlZbm2l1a4J5qZRiScj4PyFD6zfJVQrjXUemzJfRSTZa1tGpogLEyP8rz6b7/tzmOj8LxuhN+2YaYqrnnK/ImgXBL3tbsl/Ls+aUSSpq6ojNSXcgSLYvKI220ZUGZwFGdxfMtNNtjYP7/g6dtPVR2iDz8FZ0yrGyiUVJiujpJ01SgcayHOmQIPTVvXz7NAaRqvxdxFWAL6/EDL4rt1DxMxZ/63MpJDGuLLurecfWs1ae4pNDKB2mPW6BduK3/v7Tju9BFqKvIQq7FI9NkBybDGgNvEM1qS8nU9TNc2X3EZsTu1ljditoZy82efZ1oDejQq0R2p6uUB/QUc/hV457UUeaMS5K77nswKOZ+D9OTF6UDyOIJtuwejM8aH8gV0nkIeuEmZFaciTvSA7lLrCq5kC+NCP1I+tc9NqqdXN4GH5k7kzcCNcoDvTdwEkk5vOMItPH6jCiMd9r1ZLWIHjlpI70UaIMst3bgKBP44e3rZiADoAgBGUQh9O9TUGT+yBTkm5S4MsdnAL0MdHWFguZAGoG83NFghMXxynf+OVe8hcoaTB/IsFwCLjTV2HARSyOwnWFOhjHfFsJaHifXYf81F0HiTfaI6UIBnLMkpBDVMK8gklee78=
  template:
    metadata:
      name: ghcr-secret
      namespace: coreservice
    type: kubernetes.io/dockerconfigjson
