name: Trivy SBOM (CycloneDX)

on:
  push:
  pull_request:
    paths:
      - "pom.xml"
      - "**/pom.xml"
      - "src/**"
      - ".github/workflows/trivy-sbom.yml"
      - "config/trivy/**"

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Install dependencies (no tests)
        run: mvn -B -q dependency:resolve dependency:resolve-plugins

      - name: Install Trivy
        run: |
         sudo apt-get update
         sudo apt-get install -y wget
         wget https://github.com/aquasecurity/trivy/releases/download/v0.70.0/trivy_0.70.0_Linux-64bit.deb
         sudo dpkg -i trivy_0.70.0_Linux-64bit.deb

      - name: Generate SBOM (CycloneDX)
        run: |
         trivy fs . \
         --format cyclonedx \
         --output sbom.cdx

#      - name: Upload SBOM
#        uses: actions/upload-artifact@v4
#        with:
#          name: trivy-sbom-cyclonedx
#          path: sbom.cdx
